[versions]
kotlin = "1.7.20"
koin = "3.2.0"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

[plugins]
#hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
